### ISSUE TITLE
Provider: Cloudflare Stream

### ISSUE THREAD

**Issue by marcelgruber** [vidstack/vidstack#559]
https://www.cloudflare.com/products/cloudflare-stream/

https://developers.cloudflare.com/stream/

**Comment by mmiszy** [comment]
I've tried using Vidstack with Cloudflare Stream and it's not working but I can't figure out why.
The m3u8 file is fetched, length of the video is displayed, but I can't get it to play :(

**Comment by mmiszy** [comment]
Tried again now and it's working great 🔥

**Comment by thomaskant** [comment]
I don't think there's need for a new provider, Cloudflare Stream provides both, HLS and DASH files so it should work perfectly 😄

**Comment by mihar-22** [comment]
As Thomas mentioned, there's no need for a new provider as CF Stream provides a HLS manifest.
