### ISSUE TITLE
Provider: VK

### ISSUE THREAD

**Issue by Adamanthus** [vidstack/vidstack#617]
vk.com offer an iframe embed for videos on the platform. Would be nice to see it included as a provider.

**Comment by mihar-22** [comment]
Thanks for the issue! Our providers are standard (audio/video/hls) which should work with most streaming providers. If VK does not provide either of those file types and is only an embed then we won't be supporting them.

Alternatives:

- [AWS](https://aws.amazon.com/media-services/)
- [Mux](https://www.mux.com/)
- [Cloudflare Stream](https://www.cloudflare.com/products/cloudflare-stream/)
- [Api.video](https://api.video/)
