### ISSUE TITLE
NPM package is bleeding types

### ISSUE THREAD

**Issue by plauclair** [vidstack/vidstack#634]
In my project, I use `noImplicitAny`. The NPM package seems to be exporting TS files and causing `tsc` to output errors. 

```bash
$ tsc --noEmit --incremental false

node_modules/@vidstack/foundation/src/context/ContextConsumerController.ts(18,12): error TS7053: Element implicitly has an 'any' type because expression of type 'symbol' can't be used to index type 'ReactiveControllerHost & EventTarget'.
node_modules/@vidstack/foundation/src/context/ContextConsumerController.ts(29,16): error TS7053: Element implicitly has an 'any' type because expression of type 'symbol' can't be used to index type 'ReactiveControllerHost & EventTarget'.
node_modules/@vidstack/foundation/src/context/ContextConsumerController.ts(49,13): error TS7053: Element implicitly has an 'any' type because expression of type 'symbol' can't be used to index type 'ReactiveControllerHost & EventTarget'.
node_modules/@vidstack/foundation/src/logger/colors.ts(44,7): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
node_modules/@vidstack/foundation/src/logger/groupedLog.ts(16,28): error TS7053: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type '{}'.
  Property '["@vidstack/foundation/src/logger/groupedLog".GROUPED_LOG_ID]' does not exist on type '{}'.
node_modules/@vidstack/foundation/src/utils/unit.ts(8,30): error TS7006: Parameter 'a' implicitly has an 'any' type.
node_modules/@vidstack/foundation/src/utils/unit.ts(8,33): error TS7006: Parameter 'b' implicitly has an 'any' type.
```

**Comment by mihar-22** [comment]
Thanks for reporting! I'll dig into this soon, I wonder if setting [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) TS config silences it.

**Comment by plauclair** [comment]
Unfortunately it does not. I looked into it and skipLibCheck only works for `d.ts` files, not exported `ts` ones (I know right 🥲). 

This was reported and it's closed with a "works as intended" tag https://github.com/microsoft/TypeScript/issues/41883

**Comment by mihar-22** [comment]
Do you know if this is because the `exclude` config doesn't contain `node_modules` and it's picking up on the `.ts` files in there, or is it because it's following the type declaration sourcemap, or something else?

**Comment by plauclair** [comment]
I'll have a look and let you know.

**Comment by mihar-22** [comment]
Found the problem in the [`globals.d.ts`](https://github.com/vidstack/vidstack/blob/main/packages/player/globals.d.ts) file which imports from `src`. I'll patch this real soon.

**Comment by plauclair** [comment]
I was _just_ looking at this too and came here to post the same thing. :) Thanks once more!
