### ISSUE TITLE
Bug: ReferenceError thrown when click on Fullscreen button

### ISSUE THREAD

**Issue by aidenlx** [vidstack/vidstack#637]
Using latest v0.13.2, reference error is thrown when click on fullscreen button. Here is the error message: 

<img width="917" alt="image" src="https://user-images.githubusercontent.com/31102694/159724606-60bb11e0-0b7e-4cda-9baa-447b13a2a371.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/31102694/159725670-02bbe10a-3bb6-479d-8aca-4754bed7ae3a.png">

Related line: https://github.com/vidstack/vidstack/blob/c42b2924b9adc478c7bdbc1b17e6fc045a184a8e/packages/foundation/src/fullscreen/FullscreenController.ts#L139

Error Sample: https://codepen.io/aidenlx/pen/dyJOmpp

**Comment by mihar-22** [comment]
Ah missed that because I had a `// @ts-expect-error` on it becaause `fscreen` doesn't have global even types but it also meant I missed the import missing 😅 . Thanks for reporting, I'll include in next release.
