### ISSUE TITLE
Fullscreen change & error media events are not fired from media provider

### ISSUE THREAD

**Issue by dylanbussone** [vidstack/vidstack#658]
Hey Rahim!

It looks like with the recent fullscreen refactor, vds-fullscreen-change (and error) events are by default dispatched from the media controller and not the provider:
https://github.com/vidstack/vidstack/blob/main/packages/player/src/media/controller/MediaController.ts#L387-L394

Since the provider is contained within the controller, users listening to the provider for media events do not receive the vds-fullscreen-change/error events.

**Comment by mihar-22** [comment]
Thanks for reporting! I'll have a look first thing Monday.
