### ISSUE TITLE
iPad Safari fullscreen events are not working

### ISSUE THREAD

**Issue by dylanbussone** [vidstack/vidstack#661]
Hey! It seems that fullscreen events from iPad devices using Safari end up getting a consistent fullscreen error on attempt.

I looked into this a bit and it seems that it is due to the `pointerdown` listener type used in `ToggleButtonElement`. If we change this to a `pointerup` it works as expected. I am not sure if this is a Safari bug or intentional behavior (to prevent fullscreening in the middle of a possible swipe/hold action).

**Comment by mihar-22** [comment]
Ooo thanks for digging into this. Ye thinking of it now not sure why it's `pointerdown`. I'll swap it out for up. It might also explain that random play rejection issue we were looking at ages ago. The timing of the `pointerdown` probably would either reject or somehow make it.

Apologies for the delay on the other issue as well as I got hung up upgrading docs site. Getting on to it now. By the way not sure if you need it, but if you require any specific docs feel free to let me know.

**Comment by dylanbussone** [comment]
All good, thanks!
