### ISSUE TITLE
LBRY Support & Peertube Support

### ISSUE THREAD

**Issue by trymeouteh** [vidstack/vidstack#712]
**Is your feature request related to a problem? Please describe.**
There is no easy way to make a video or audio player for LBRY and Peertube videos and audios.

**Describe the solution you'd like**
An easy way to integration with LBRY and Peertube just as there is built in easy integration with YouTube and Vimeo.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/sampotts/plyr/issues/2595

**Comment by mihar-22** [comment]
Thanks for reporting! We're only supporting standard providers at this time (audio/video/hls/dash). There's no plans to add embed support at the moment.
