### ISSUE TITLE
Architecture Docs

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#732]
### URL:

https://www.vidstack.io/docs/player/core-concepts/architecture

### Describe:

We haven't added anything yet. It might be best to have some diagrams and show the relationship between the player, controller delegate, providers/adapters, and finally how state updates are handled with request events and the store.

**Comment by pietrop** [comment]
>We haven't added anything yet. It might be best to have some diagrams and show the relationship between the player, controller delegate, providers/adapters, and finally how state updates are handled with request events and the store.

I think that would be great, thanks!


Something that would also be helpful (not sure if it fits in architecture thou or if you have already tackle this elsewhere, or even if it is what you are describing above tbh) is a conceptual overview of the mental model for the player. Something that if a contributor wants to go beyond the black box usage, and make a PR for a feature suggestion or bug fix they find their way around the codebase, if that makes sense?

**Comment by mihar-22** [comment]
Ye makes perfect sense @pietrop, the architecture guide would probably only serve as background reading for contributors, we'd need a proper contributor guide. It's tricky because the tooling is new and I'm learning my way through it in real-time. I have pretty good ideas on how to refactor most of this to make it feel more like traditional web components so that existing knowledge can be leveraged. I'm planning on simplifying parts of the codebase and building a contributor guide once I get through most of the work up to skins. 

If you have any suggestions or things that currently need clarification feel free to list them here to help us build a better guide.

**Comment by mihar-22** [comment]
Thanks for all the feedback! No need for this issue anymore as we're working on it as part of the new 1.0 docs. We've noted down any suggestions here :)
