### ISSUE TITLE
Vue Integration

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#747]
This work will mostly take place in Maverick but we need to add specific state management hooks for reading, subscribing, and updating media state. We should also add any additional helpful hooks for getting the player etc.

**Comment by Velka-DEV** [comment]
Hello @mihar-22, is there any pre-defined specification defined for the vue integration? I would like to contribute to this

**Comment by mihar-22** [comment]
Unfortunately nothing at the moment @Velka-DEV. I have something I'm working on that might smooth out Vue integration. I'll dive into it a little more after this next release.

**Comment by Velka-DEV** [comment]
Okay no problem, ping me when you are ready to go if you want some help.

**Comment by connecteev** [comment]
Hey @mihar-22 thanks for your work on vidstack. When is this expected to go live? vue integration is important and therefore a deal breaker for me

**Comment by mihar-22** [comment]
Since `1.0@next`, we now include JSX types for our Custom Elements in Vue. A dedicated Vue integration will be decided upon at a later time in which I'll create a new issue. Our new installation docs and [Vue examples](https://github.com/vidstack/examples/tree/main/player/vue) should get you going in the right direction!

**Comment by mostafaznv** [comment]
@mihar-22 
This library is amazing. It would be nice if it had official support for Vue and Nuxt, similar to React.

**Comment by mihar-22** [comment]
Eventually we will, I just have way too much on my plate. The new library works really well with Vue, you won't notice any difference to be honest. We have no Shadow DOM and are headless so it also works with Nuxt + SSR.
