### ISSUE TITLE
Vue Docs

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#748]
Following https://github.com/vidstack/player/issues/747 we need to add docs for Vue. 

Custom Vue Pages:

- Installation
- Components
- State Management

The rest will be updating snippets across the site.

**Comment by connecteev** [comment]
Eagerly waiting for this!

**Comment by mihar-22** [comment]
Since `1.0@next`, we now include JSX types for our Custom Elements in Vue. A dedicated Vue integration will be decided upon at a later time in which I'll create a new issue. Our new installation docs and [Vue examples](https://github.com/vidstack/examples/tree/main/player/vue) should get you going in the right direction!
