### ISSUE TITLE
SvelteKit Examples

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#766]
- [ ] Community Skin Example
- [ ] Headless Tailwind Example

**Comment by marksteven** [comment]
Initially tried the React example for a live stream on svelte which failed (looking for react packages) . 
Then found the thread for svelte so will assume svelte is not supported as yet?

**Comment by mihar-22** [comment]
Not yet @marksteven, it's on our roadmap for the `0.7` release.

**Comment by marksteven** [comment]
Excellent. 
The old? version Vime works well for video file but not - at least for me - a streaming file eg M3U8 type.
Good luck with it.
Look forward to this being solved.

**Comment by mihar-22** [comment]
Closing this as we now have [Svelte examples](https://github.com/vidstack/examples/tree/main/player/svelte) which should be mostly the same for SvelteKit.
