### ISSUE TITLE
Basic example does not work with Parcel

### ISSUE THREAD

**Issue by vladinator1000** [vidstack/vidstack#782]
### Current Behavior:

Hi folks, if I follow the [getting started instructions](https://www.vidstack.io/docs/player/getting-started/installation), the library doesn't load when using the Parcel bundler.
```
🚨 Build failed.

@parcel/core: Failed to resolve 'vidstack' from 
'./node_modules/@vidstack/react/dist/prod.js'
```

### Expected Behavior:

The basic React example [from the docs ](https://www.vidstack.io/docs/player/getting-started/installation) should work.

### Steps To Reproduce:
1. Install parcel
2. Create a basic react app
3. Import Vidstack

Reproduction example: https://github.com/vladinator1000/vidstack-example-bug

### Environment:
```
  "dependencies": {
    "@vidstack/react": "0.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "vidstack": "0.3.2",
    "typescript": "4",
    "parcel": "2.8.3"
  },
```
- Framework: React
- Meta Framework: Vanilla
- Node: 18
- Device: PC
- Browser: Firefox

**Comment by mihar-22** [comment]
This issue is outdated now since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
