### ISSUE TITLE
Media mute button requires double click to toggle it's state 

### ISSUE THREAD

**Issue by dominictwlee** [vidstack/vidstack#827]
### Current Behavior:
On page load, before player has started playing, the media mute button requires double clicking before it's able to toggle on/off.

Once audio is playing, the mute button seems to behave as normal (single click on/off).

Not sure whether this is only related using vidstack in a Wails app (desktop app framework, similar to Electron but with Go backend).

### Expected Behavior:
Mute button should toggle on/off with a single click regardless of media player state.

### Steps To Reproduce:
1. Install wails CLI.  https://wails.io/docs/gettingstarted/installation
2. Clone minimal repro: https://github.com/dominictwlee/vidstack-repro-mute
3. `cd frontend`
4. `npm install`
5. `cd ..`
7. `wails dev`

### Environment:
- Framework: React
- Meta Framework: Wails/Vite
- Node: 16.16.0
- Device: Desktop
- OS: Pop!_OS 22.04 LTS (Linux/Ubuntu)
- Browser: WebView (webkit2gtk)

### Anything Else?
Hard to show behavior in screenshot. Try clicking/double clicking the mute button in the minimal repro.

**Comment by mihar-22** [comment]
This issue is outdated now since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
