### ISSUE TITLE
MKV and ass subtitle and fonts support

### ISSUE THREAD

**Issue by Rise-KuN** [vidstack/vidstack#833]
If the player will support subtitles in the future why not support MKV with embedded fonts and ass/ssa/srt subtitle, that will be cool feature

**Comment by mihar-22** [comment]
Not 100% sure, but I think MKV is supported in most browsers if using supported audio/video codecs. I'd have to test this... but at the moment we can play containers/codecs that are supported by browsers (not determined by us). 

There was an interesting idea in Discord about using `ffmpeg-wasm` to transmux (i.e., repackage) clients-side to see if we can get unsupported formats working. Going a step further and transcoding would be too expensive client-side and introduce delays. Maybe if it can be done in segments and streamed but again that would need testing.
