### ISSUE TITLE
[Community Skin] Media time formatting doesn't pad minutes

### ISSUE THREAD

**Issue by codercms** [vidstack/vidstack#860]
v0.6.4

![image](https://github.com/vidstack/player/assets/4526911/4e1edb09-3a92-4623-ae6e-895d34ee1f96)

Similar to https://github.com/vidstack/player/issues/852

**Comment by mihar-22** [comment]
Strange, just tested and it works...?

<img width="53" alt="image" src="https://github.com/vidstack/player/assets/14304599/29bbc5ba-11e9-4bc2-a04d-3e317e29105e">

**Comment by JorrinKievit** [comment]
Hm i have the same issue 🤔 . I am on 0.6.10. 
For me it is only on the time slider hover using the Community Skin:

![image](https://github.com/vidstack/player/assets/43169049/d21ff2ce-4c4d-447d-b378-1d37e1af7d09)
![image](https://github.com/vidstack/player/assets/43169049/07220074-3b7b-432e-8047-5c7544f53097)

**Comment by pravic** [comment]
Same here.

Does [pad-minutes](https://www.vidstack.io/docs/player/components/sliders/slider-value#props_padminutes) help?

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
