### ISSUE TITLE
Player show NAN mbps if bitrate not specified in HLS playlist.

### ISSUE THREAD

**Issue by Senkai350** [vidstack/vidstack#869]
### Current Behavior:
Player show NAN mbps in quality menu when bitrate not specified in HLS playlist.

### Expected Behavior:
Player doesn't show bitrate at all. Only quality.

### Steps To Reproduce:
Use any HLS playlist without specified bitrate.
for example this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:RESOLUTION=640x360
specify your own link here
#EXT-X-STREAM-INF:RESOLUTION=640x480
specify your own link here
#EXT-X-STREAM-INF:RESOLUTION=1280x720
specify your own link here

Example: steps to reproduce the behavior:
Go to quality menu, when player already loaded HLS playlist with no bitrate, see NaN mbps

### Environment:
- Framework: Vue
- Device: PC
- OS: Windows 10

### Anything Else?
Links? Screenshots?
![изображение_2023-06-29_235855593](https://github.com/vidstack/player/assets/89925616/e751f6a9-479d-47d8-877f-1b486d24d4ce)

**Comment by mihar-22** [comment]
This issue is outdated now since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
