### ISSUE TITLE
Benchmark Tests

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vidstack#87]
## Tasks

- [ ] Investigate whether this type of testing would be valuable.
- [ ] **If valuable.** Setup benchmark tests using Tachometer.

## References

- https://github.com/Polymer/tachometer
- https://github.com/vidstack/player/blob/main/docs/architecture/overview.md#testing

**Comment by tomByrer** [comment]
Amount of memory, CPU, & start time used are helpful, esp when dealing with mobile devices.

**Comment by mihar-22** [comment]
No plans for this anymore, I'll reopen when we decide to add specific benchmarks in the future. This will most likely be part of our official post-1.0 work. We're now at `1.0@next`, [see latest release notes](https://github.com/vidstack/vidstack/discussions/935).
