### ISSUE TITLE
Preload metadata does not truly preload the metadata

### ISSUE THREAD

**Issue by sovrgn** [vidstack/vidstack#871]
### Current Behavior:

When the <MediaPlayer/> in Next JS is setup with preload='metadata' and the displayed element is off screen, the metadata is not loaded (in other words, I cannot get duration of the video/audio files if they are not in viewport).

For comparison I tried it with normal html audio tag and it in fact preloads the metadata and I am able to get the duration, even when the element is out of screen.

For both scenarios the element was in the same position in the DOM and the same distance out of screen.

### Expected Behavior:

Metadata should be preloaded (when specified as a <MediaPlayer/> prop) and properties like dimensions and duration should be available even when element is out of viewport.

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 18.15.0
- Device: MacBook Air (M1)
- OS: Monterey@12.5
- Browser: Chrome@113.0.5672.126 (Official Build)

**Comment by mihar-22** [comment]
Thanks for reporting! You will need to set the `load` strategy of the player to `eager`. The default is `visible` hence why preload is doing nothing.

```tsx
<MediaPlayer load="eager">
```
