### ISSUE TITLE
Autoplay not working on iPhone 11/X/XS

### ISSUE THREAD

**Issue by el-schneider** [vidstack/vidstack#875]
### Current Behavior:

The video isn't autoplaying

### Expected Behavior:

the video in the below example should autoplay, like it does on iPhone 8/12/13/14

### Steps To Reproduce:

check this out: https://codepen.io/el-schneider/pen/xxQXdOb

### Environment:
- Device: iPhone@11
- OS: iOS@16.5/13.3
- Browser: Safari/Chrome

### Additional Info

Maybe this has to do with: https://webkit.org/blog/6784/new-video-policies-for-ios/ and could be solved by adding the `muted` attribute to the `video` element

**Comment by mihar-22** [comment]
This issue is outdated now since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
