### ISSUE TITLE
Unable to scroll touching on the video component

### ISSUE THREAD

**Issue by arindammitra06** [vidstack/vidstack#880]
### Current Behavior:

Hi, Thanks for the awesome library. I am trying to use it for a project where there are multiple video feeds. I am using the community skin, what I noticed is that on a mobile view (iphone or even chrome mobile view) i am unable to scroll down touching on the video component. It toggles the transition to show/hide play button. Below is the javascript error i am getting on console.

[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
passive @ media-core.js:3363

### Expected Behavior:
The page should scroll and only toughing individual buttons should trigger events.

### Steps To Reproduce:
Switch chrome to mobile view so that video occupies the width of the screen. Try scrolling.
### Anything Else?
Couldn't take a proper screenshot, but this is how the video covers the screen.
<img width="359" alt="image" src="https://github.com/vidstack/player/assets/5446217/aa9f8f05-880e-41c1-ac3b-ea14ac07f298">

**Comment by eeshankeni** [comment]
Same here :(

**Comment by arindammitra06** [comment]
Is this package even maintained?

**Comment by mihar-22** [comment]
Yes. Thanks for reporting the issue. I’m just working on a large release and my plate is full, I’ll tend to issues right after.

**Comment by arindammitra06** [comment]
Thank You. We can wait for sure :-)

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.

**Comment by ljs19923** [comment]
Hello, I have the same poblem on iOS :/

"@vidstack/react": "^0.6.14",
