### ISSUE TITLE
PiP issues due to unmounting of video element.

### ISSUE THREAD

**Issue by jontyparab** [vidstack/vidstack#883]
### Current Behavior:

Currently the video element is unmounted when the src is empty. This causes issues with Picture-In-Picture, as a new video element is added to the DOM for new src which causes the linking between the PiP view and the video element to break. Hence user will have to again press the PiP button to enter into PiP view which is not ideal. Note that changing the src directly to a new src (without an intermediate empty src) keeps the video element mounted which works as expected.

### Expected Behavior:

The video element (media-player) should accept empty source without unmounting video element (I am not sure if there is already a way to do that or not).  This will allow to continue the next videos in the same PiP view without requiring a user interaction again.

### Steps To Reproduce:

DEMO Link: https://codepen.io/jonty99/pen/VwVpOPB?editors=1111

1. Play a video element with src
2. Enter PiP (do this and below steps manually in the demo)
3. Empty the video src
4. Unmount and remount the video

### Environment:

- Framework: Vue
- Node: v18.13.0
- Device: Desktop
- OS: Ubuntu 22.04.2 LTS
- Browser: Chrome@114

### Anything Else?

I have tried to overcome it by programmatically closing and reopening PiP but since it is gated by [UserActivation](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation) it will still require user interaction in some form.

Screenshots:
![image](https://github.com/vidstack/player/assets/64889444/feecac64-b8de-4473-91d0-e0e3aa7f49ba)

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
