### ISSUE TITLE
Community skin's dark overlay affects video colours

### ISSUE THREAD

**Issue by moretti** [vidstack/vidstack#886]
### Current Behaviour:

Hello, I recently started using the latest version of Vidstack and noticed that the new community skin has a dark overlay applied to the video. Removing this overlay makes the controls less visible on white backgrounds. On the other hand, keeping the overlay changes the video colours, making them appear darker than expected.

You can see an example here:

Screenshot 1 (default dark overlay - colours appear darker):
![Screenshot 1](https://github.com/vidstack/player/assets/1186409/6dedb6c5-fe04-4f00-a823-3fcb5f4b7e16)

Screenshot 2 (overlay removed - controls less visible on white backgrounds):
![Screenshot 2](https://github.com/vidstack/player/assets/1186409/0cd182a7-c657-489c-ba4b-a112ec5507be)

### Expected Behaviour:

The expected behaviour is to have a community skin that maintains the original colours of the video while ensuring that the player controls remain visible and clear, even on white backgrounds.

### Steps To Reproduce:

1. Use the latest version of vidstack.
2. Apply the community skin with the dark overlay.
3. Observe the impact on video colours and control visibility.
4. Remove the dark overlay by commenting out the following line:
https://github.com/vidstack/player/blob/b57db0be1768a6f8c852c068df42b6fc32fda375/packages/vidstack/src/player/skins/community/video.css#L54  and observe the changes in video colours and control visibility again.

**Comment by moretti** [comment]
@ewenmic, @mihar-22 Thank you for pointing me in the right direction, that works perfectly! 
I'm excited to see the upcoming changes. In the meantime, I'll follow your advice and customise the scrim based on #873.

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
