### ISSUE TITLE
Overflow issues stemming from media-menu

### ISSUE THREAD

**Issue by yuvalkarmi** [vidstack/vidstack#887]
### Current Behavior:

`media-menu` components get appended to global body of the DOM. These components currently have a `position: relative` and end up causing global vertical overflow (scrollbars) even if the visible content of the page is shorter than the height of the viewport.

### Expected Behavior:

No extra overflow should be added to the window. `media-menu` components should have `position:absolute` as they open up as flyover menus.

### Steps To Reproduce:

1. Embed Vidstack in a React app with material UI
2. Observe overflow even on pages where the content is shorter than the height of the viewport

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 18
- Device: Google Chrome (narrow window)
- OS: Mac
- Browser: Chrome@114

### Anything Else?

Until this is fixed in Vidstack, you can fix in your code by adding a *global* style like this:
```css
media-menu: {
  position: absolute;
}
```

Or if using MUI (material UI) as I am:
`import { GlobalStyles } from '@mui/material';`

And in your render method:
```javascript
<GlobalStyles
  styles={{
    'media-menu': {
      position: 'absolute',
    },
  }}
/>
```

**Comment by mihar-22** [comment]
Thanks for reporting! This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
