### ISSUE TITLE
Replay button is missing tooltip text

### ISSUE THREAD

**Issue by Curetix** [vidstack/vidstack#888]
### Current Behavior:

The repeat button, which replaces the play/pause button after a video ends, does not have any tooltip text when hovering over it.

![firefox_joULLtLNFw](https://github.com/vidstack/player/assets/15160542/5898de70-eba4-4ab7-bba8-41884e8e6777)

The community skin translation also does not a key for this, so it was probably completely overlooked.

### Expected Behavior:

The tooltip should have a text like "Replay" or "Repeat".

**Comment by mihar-22** [comment]
This should be resolved now in `1.0@next`, let me know if the issue persists!
