### ISSUE TITLE
media-volume-slider value unable to be set programatically 

### ISSUE THREAD

**Issue by s-moran** [vidstack/vidstack#899]
### Current Behavior:

When trying to set the slider value programatically, updates are not reflected on the UI or the provider

### Expected Behavior:

Setting the slider value with javascript should trigger a change in the UI and adjust the volume of the provider. 

This needs to be supported in order to persist a user's slider state between browser refreshes, e.g. using `localStorage`. The [slider API docs](https://www.vidstack.io/docs/player/components/sliders/slider#api_props) suggest that setting `value` is supported. 

### Steps To Reproduce:
HTML:
```html
    <media-player>
      <media-outlet style="visibility:hidden">
      </media-outlet>
      <div>
        <media-play-button></media-play-button>
        <media-mute-button></media-mute-button>
        <media-volume-slider></media-volume-slider>
      </div>
    </media-player>
```
Javascript:
```typescript
const volumeSlider = document.querySelector('media-volume-slider');
volumeSlider.onAttach(() => {
  volumeSlider.value = 50;
})
```
### Environment:
- Framework: Angular 16 with vidstack web components
- Meta Framework: n/a
- Node: 18
- Browser: Chrome

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
