### ISSUE TITLE
Web component compilation errors when importing MediaRemoteControl

### ISSUE THREAD

**Issue by s-moran** [vidstack/vidstack#900]
### Current Behavior:

In Angular 16, importing objects from top-level vidstack causes compilation errors due to missing hls.js and WebkitPresentationMode:
```
Cannot find module 'hls.js' or its corresponding type declarations.
Cannot find name 'WebKitPresentationMode'
``` 
![image](https://github.com/vidstack/player/assets/17832202/5ef8667d-83e1-4ed0-be58-1d6d080a003a)

### Expected Behavior:

Import should not depend on these other objects and compilation should proceed normally

### Steps To Reproduce:
Compile an Angular component with the following import:
```typescript
import { MediaRemoteControl } from 'vidstack';
```

### Environment:
- vidstack version: 0.6.13
- Framework: Angular 16 (Web components)
- Node: 18.10.0

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
