### ISSUE TITLE
audio/mp3 not working 

### ISSUE THREAD

**Issue by eemi2010** [vidstack/vidstack#914]
Hello there,
Thank you all for your great work and this great lib.

Looking at https://github.com/vidstack/player/blob/main/packages/vidstack/src/utils/mime.ts, it looks like the type "audio/mp3" is not supported. Which will return false in the "canPlay" method in the https://github.com/vidstack/player/blob/main/packages/vidstack/src/player/providers/audio/loader.tsx file. 

The audio file will never load if the URL does not end with ".mp3" (dynamic url generated at server serving a mp3 file).

Is this by design ?

**Comment by mihar-22** [comment]
Thanks for reporting! Yes this is by design. We now check headers to see if we can figure out the media type, however, the best thing to do in these situations is to provide a src `type` hint:

```ts
player.src = { src: '...', type: 'audio/mp3' }
```
