### ISSUE TITLE
Hls playlist not working on IOS

### ISSUE THREAD

**Issue by paolodelfino** [vidstack/vidstack#918]
### Current Behavior:

I'm trying to watch a video using a m3u8 playlist and it's working fine on desktop, but on my iPhone, it doesn't load the video.
Playlist: ```https://vixcloud.bz/v2/playlist/164645?token=oxuMYFd1b4BGOiJdP0HDlA&token720p=ntYXtp45dOy1ibgxQYumTw&token360p=&token480p=IasrZHpfQ3-uQxbNIPoRZQ&token1080p=&expires=1699219435&canCast=1&n=1```
If the time you're reading it's expired, I can generate another of it.

The problem happens to be with the playlist because if I use the vidstack's test one ```https://media-files.vidstack.io/hls/index.m3u8``` it works, but at the same time it should be due to how vidstack handles hls, because simply using hls.js and video element it works.

### Expected Behavior:

Video playing on iPhone too.

### Steps To Reproduce:

Using React
```js
<MediaPlayer
      className="w-full h-full"
      src={playlist}
      aspectRatio={16 / 9}
      crossorigin=""
    >
      <MediaOutlet></MediaOutlet>
      <MediaCommunitySkin />
</MediaPlayer>
```
where playlist is the URL above.

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 16.0.0
- Device: iPhone@12 Pro Max
- OS: iOS@16.6
- Browser: Safari@latest

**Comment by mihar-22** [comment]
Thanks for reporting! This is because the `.m3u8` file extension is not provided so the provider selection process is failing. You can specify a `type` hint in this case:

```ts
<MediaPlayer src={{ src: "...", type: "application/x-mpegurl", }}>
```

Let me know if the issue persists, happy to reopen.
