### ISSUE TITLE
bug with chapters

### ISSUE THREAD

**Issue by lapsedisk** [vidstack/vidstack#921]
![Screenshot_1](https://github.com/vidstack/player/assets/134724835/95559411-b899-4df2-85cf-9da856db3daa)

Pointed incorrectly on the timeline. And the menu shows the correct minutes

**Comment by mihar-22** [comment]
There's unfortunately not enough information in this issue for me to repro or fix it. If you can provide more info such as a sample chapters VTT file (doesn't have to be the original) then I'm happy to test and try to fix it.

Thanks!
