### ISSUE TITLE
Missing Settings menu in Audio

### ISSUE THREAD

**Issue by BleedingDev** [vidstack/vidstack#922]
### Current Behavior:
Settings menu is out of the screen/invisible when resolution is bigger than 1230, e.g. 1231 x 1080. It looks like the layout needs to be one line.

### Expected Behavior:
Perfectly visible Settings menu

### Steps To Reproduce:
1. Create Audio player with Community Skin
2. Open Settings menu in resolution 1231x1080, layout is single line
<img width="347" alt="image" src="https://github.com/vidstack/player/assets/12586960/d3fe5ee4-0c67-4ecd-bf6a-98c2632f3f7c">

3. Menu is missing
4. Lower resolution to 1230x1080, layout switched to multiple lines
<img width="313" alt="image" src="https://github.com/vidstack/player/assets/12586960/c8372a36-69e2-4bba-be91-aa33525c6103">

6. Menu is visible (but down on the screen)

### Environment:
- Framework: React
- Meta Framework: Next.js
- Node: 20.6.1
- Device: Asus ROG Flow X16
- OS: Windows 11
- Browser: Edge @ 116.0.1938.76 (Official build) (64-bit) 

### Anything Else?
One row layout (menu missing):
<img width="712" alt="image" src="https://github.com/vidstack/player/assets/12586960/01c3e323-3579-4ce0-bcfc-181f9f68ab48">

Multiple rows layout (menu visible):
<img width="647" alt="image" src="https://github.com/vidstack/player/assets/12586960/c0fb2904-972d-4c8d-a7ed-388e9ae9d4b7">

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
