### ISSUE TITLE
thumbnails black screen but different size

### ISSUE THREAD

**Issue by fragilebanana16** [vidstack/vidstack#929]
<MediaPlayer style={{
        width: 1080,
        height: 720,
        position: 'absolute', left: '50%', top: '50%',
      transform: 'translate(-50%, -50%)',
      }}
        title="Sprite Fight"
        src={`http://xxxx/videos/${videoId}`}
        thumbnails="http://xxxx:3001/1.vtt"
        aspectRatio={16 / 9}
        poster={`http://xxxx:3001/${videoId}.png`}
        crossorigin=""
      >
      {/* <MediaThumbnail time="50">

      </MediaThumbnail> */}
        <MediaOutlet>
          <MediaPoster
            alt="Girl walks into sprite gnomes around her friend on a campfire in danger!"
          />

        </MediaOutlet>
        <MediaCommunitySkin />
      </MediaPlayer>

1.vtt:

WEBVTT

00:00:00.000 --> 00:00:01.000
storyboard.jpg#xywh=0,0,180,101

00:00:01.000 --> 00:00:55.000
storyboard.jpg#xywh=0,0,180,101

00:00:56.000 --> 00:04:55.000
storyboard.jpg#xywh=0,0,180,101

I put 1.vtt and storyboard.jpg under server public dir, but got black thumbnail

**Comment by mihar-22** [comment]
This issue is outdated now and should be resolved since our new [`1.0@next` release](https://github.com/vidstack/vidstack/discussions/935). If the issue persits after upgrading, feel free to let me know here and we can reopen. If the issue has changed then please open a new one.
