### ISSUE TITLE
Getting this error  [maverick] component instance has not attached yet, wait for event like so

### ISSUE THREAD

**Issue by kumarajay0412** [vidstack/vidstack#931]
Uncaught Error: [maverick] component instance has not attached yet, wait for event like so:

const el = document.querySelector('media-menu');
el.addEventListener('attached', () => {
  el.close(...)
}, { once: true });

    at MaverickElement._throwAttachError (chunk-FIEGXSET.js:1236:1)
    at proto.<computed> [as close] (chunk-FIEGXSET.js:998:1)
    at media-ui.js:2080:1

**Comment by mihar-22** [comment]
Thanks for reporting! This issue is outdated now as we've upgraded Maverick and handle attaching differently now. Let us know if any issue persists in `1.0@next`, happy to reopen.
