### ISSUE TITLE
Vidstack (React) / maverick does not work within an iframe

### ISSUE THREAD

**Issue by giliamverheide** [vidstack/vidstack#932]
### Breaking Behavior:

Rendering Vidstack's `MediaPlayer` inside an iframe does not work within an iframe and breaks the page.

### Steps To Reproduce:

Tested with [`react-frame-component`](https://www.npmjs.com/package/react-frame-component) and also a native iframe and making sure it only renders on the client and when the iframe has actually loaded.

See: https://codesandbox.io/p/sandbox/vidstack-react-iframe-39pd2g?file=/app/page.tsx:1,1
Also see [native iframe](https://codesandbox.io/p/sandbox/vidstack-react-iframe-39pd2g?file=/app/native-iframe/page.tsx:1,1) (app/native-iframe/page.tsx)

Looking at the error call stack this may be caused by maverick.

```
Unhandled Runtime Error
TypeError: this._element.onEventDispatch is not a function

Call Stack
CustomElement.componentDidMount
node_modules/maverick.js/dist/dev/react.js (84:0)

commitClassLayoutLifecycles
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (20127:0)

commitLayoutEffectOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (20299:0)

recursivelyTraverseLayoutEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (21808:0)

commitLayoutEffectOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (20285:0)

recursivelyTraverseLayoutEffects
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (21808:0)

commitLayoutEffectOnFiber
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (20455:0)

and so on...
```

If I'm not mistaken the error refers to this part in the code:

https://github.com/maverick-js/maverick/blob/a069f3fdd5268cd7acf3f052079eabbcb5ba1bbe/packages/maverick/src/react/client-component.ts#L40-L47
```ts
      _component.$$[ON_DISPATCH] = function onDispatch(event: Event) {
        let callbackProp = `on${kebabToPascalCase(event.type)}`,
          args = !isUndefined((event as CustomEvent).detail)
            ? [(event as CustomEvent).detail, event]
            : [event];

        props[callbackProp]?.(...args);
      };
```

### Environment:

- Framework: React 18.2.0
- Meta Framework: Next.js ^13.4.12
- Node: 18.18.0
- Browser: Chrome
- vidstack: ^0.6.13
- @vidstack/react: ^0.6.13

**Comment by mihar-22** [comment]
Thanks for reporting! This issue should be resolved in `1.0@next`, if not feel free to let me know and we can re-open.
