### ISSUE TITLE
Content not centered when aspect ratio is set

### ISSUE THREAD

**Issue by JorrinKievit** [vidstack/vidstack#936]
### Current Behavior:
When i set the aspect ratio on the component like this:
`aspectRatio="16/9"`
The content in the player is not centered.

### Expected Behavior:

The content is supposed to be centered, like it did in the versions before 1.0.

### Steps To Reproduce:

Use a file that has a different aspect ratio. Use aspectRatio="16/9" on the component.

### Environment:

- Framework: React
- Node: 18.0.0
- Browser: Electron

### Anything Else?
![image](https://github.com/vidstack/vidstack/assets/43169049/e8d57887-af21-424a-8019-2c19561070d5)

**Comment by JorrinKievit** [comment]
Oh something to add, the content is also stretched in full screen instead of showing black bars top and bottom 😄

**Comment by mihar-22** [comment]
Thanks for reporting! I'll have a look at this today/tomorrow 👍

**Comment by JorrinKievit** [comment]
Hey @mihar-22 , don't wanna be annoying but the issue still persists 😄 . Fullscreen is fixed, but the other issue still occurs. Seems to center correctly when I display: inline-flex on the data-media-provider instead of data-media-player 🤔

**Comment by JorrinKievit** [comment]
@mihar-22 here is a repro 😄 https://stackblitz.com/edit/vidstack-examples-jdv4nw?file=src%2Fplayer.tsx
Doesn't seem to happen for every file 🤔

**Comment by mihar-22** [comment]
I think I got it, it'll be available in the next release shortly today.
