### ISSUE TITLE
Seeking an mp4 source cause the video to restart from beginning

### ISSUE THREAD

**Issue by mattiaz9** [vidstack/vidstack#941]
### Current Behavior:

Manually setting the video `currentTime` cause the video to restart from the beginning when playing an mp4 source (it doesn't happen with an hls source).

This is the case by using the provided `TimeSlider` component, as well as directly setting `currentTime` on the video element or the player instance store.

### Expected Behavior:

It should change the current time without restarting the video.

### Steps To Reproduce:

Example component:
```tsx
function Player({ src }) {
  return (
    <MediaPlayer
        className="w-full"
        aspectRatio="16 / 9"
        src={{
          type: "video/mp4",
          src,
        }}
        crossorigin="anonymous"
      >
        <MediaProvider />

        <TimeSlider.Root className="mb-4">
          <TimeSlider.Track className="h-2 bg-gray-800">
            <TimeSlider.TrackFill className="bg-primary-700" />
            <TimeSlider.Progress className="bg-primary-500" />
          </TimeSlider.Track>
          <TimeSlider.Thumb className="h-3 w-3 rounded-full bg-white" />
        </TimeSlider.Root>

        <PlayButton>play</PlayButton>
      </MediaPlayer>
  )
}
```

Trying to manually seek a video to a certain timestamp by clicking on the time slider cause the video to restart.

Also:
`document.querySelector('video').currentTime = 5`

cause the video to restart.

### Environment:

Example:
- Framework: React
- Meta Framework: Vite
- Node: 20.2.0
- Device: MacBook Pro
- OS: macOS@14
- Browser: Chromium@117

**Comment by mihar-22** [comment]
This _might_ be related to your video or how it's being served, and not the player. Does this work fine with the standard `<video>` element? If it does then we can start investigating deeper.

**Comment by mattiaz9** [comment]
thanks @mihar-22, it looks like a problem the video source indeed.
