### ISSUE TITLE
Migration guide / official docs

### ISSUE THREAD

**Issue by Mister-Hope** [vidstack/vidstack#943]
I understand that though vidstack touch v1, it's publishing on next channel, but as we are using stable version numbers like `1.1.9` instead of `1.0.0-alpha.19`, can we at least show users how to migrate from 0.6 to 1.0?

Here is my problem, in the previous v0.x, we use `media-outlet` to hold things like `<sources>` and `<track>`, but there is no more `media-outlet` in v1 anymore, and I am not seeing a single word how to migrate to v1 `<media-provider>` in the [blog post](https://github.com/vidstack/vidstack/discussions/935).

This is open source and I do open source to, I am not trying to push anyone for anything, but I think currently this project reaction could confuse most people (as long as they are not sticking to source code changes while there is a huge change from 0.6.x to v1).

My suggestions are (take 1 of them should be fine):

- Add a detailed migration docs to tell people how migrate to v1 from v0.6 very soon, then complete the docs through timeline. People at least can know something with the old docs and migration guide

- Complete docs of any new concept in v1 immediately, so that users can make comparison with old docs and guess to understand the migration.

Anyway, I think it's not affordable for any project to use a stable version number while not providing both basic docs and migration guide.

**Comment by mihar-22** [comment]
This is on `1.0@next`, it's a pre-release (not main). I don't want users adopting the old `0.6.x` hence why we're pushing forward. On the surface not too much has changed, if you walk through the [new installation docs](https://www.vidstack.io/docs/player/getting-started/installation?styling=default-layout&provider=video) you'll get set back up in no time. I've also covered the [Default Layout](https://www.vidstack.io/docs/wc/player/components/layouts/default-layout?styling=default-theme) and added all component API references/examples. In addition, nearly all of the old player APIs are still in place, so you can even use the old docs to guide you. The `media-outlet` has changed to `media-provider`, simple name change.

There's a comprehensive [examples repo](https://github.com/vidstack/examples) too which should guide you on how to set up your player for whatever framework and styling library. I'm starting work on finishing the remaining docs tomorrow, it shouldn't take me too long. You have to forgive me, there's a lot of work on my plate so some things take a little longer than even I like.

**Comment by mihar-22** [comment]
Lastly @Mister-Hope, if you need any help I'm available on our [Discord](https://discord.gg/QAjfh2gZE4) channel to ask questions.

**Comment by Mister-Hope** [comment]
> The media-outlet has changed to media-provider, simple name change.

I think it would be great if you can list the changes and add a migration guide, no need to cover all changes, but basics like media-community-skin changed to media-audio/video-layouts.

**Comment by Mister-Hope** [comment]
> This is on 1.0@next, it's a pre-release (not main).

Note I am not trying to blame you or argue something, but most (>95% populatr libs) will use `-alpha` or `-beta` for early feedback, and when an actual stable version syntax is used (like vue3 on mext channel), basic functionality (vidstack has) and basic docs/migration docs (I am asking) are provided.

**Comment by mihar-22** [comment]
You're right and I've been pushing ahead faster then what a normal project would because of certain time constraints. I generally document changes but I skipped it this time because the changes felt minimal, and I felt the installation docs and examples covered it all well. I understand that's a bad assumption but I went with it to speed up. Apologies for any confusion.

I'll try to put together a minimal migration guide 👍 If I don't have time, then I'll definitely make sure in the future to roll out migration guides. We won't do big quick changes from here forward as we're stable now and can't afford to break anything.

**Comment by Mister-Hope** [comment]
> I'll try to put together a minimal migration guide 👍 If I don't have time, then I'll definitely make sure in the future to roll out migration guides. We won't do big quick changes from here forward as we're stable now and can't afford to break anything.

Looking forward🎉, honestly I am watching this repo, and I wait quite a long time for docs completion till the v1.0 release before opening this issue.😅

**Comment by mihar-22** [comment]
Ye I know, the docs really needs to finish. It's on my mind constantly. I've been addressing bugs, helping people, and doing other work. I finished resolving main issues it seems, so docs is 100% my focus now. Thanks for your patience!

**Comment by mihar-22** [comment]
Here you go @Mister-Hope: https://github.com/vidstack/vidstack/discussions/949. Let me know if we can make it better.

**Comment by Mister-Hope** [comment]
I think it's already a good one to get started with v1
