### ISSUE TITLE
Poster will not work if using https://thumbnail.video/api/

### ISSUE THREAD

**Issue by reyamir** [vidstack/vidstack#948]
### Current Behavior:

When set poster component with thumbnail generated by https://thumbnail.video/api/, it will not show

![Screenshot 2023-10-10 150603](https://github.com/vidstack/vidstack/assets/123083837/a9f5fdf8-9675-4f17-a615-793f2739a322)

### Expected Behavior:

Show poster

### Steps To Reproduce:

Set poster like this

```js
<MediaProvider>
  <Poster
    className="vds-poster"
    src={`https://thumbnail.video/api/get?url=${url}&seconds=1`}
    alt="poster"
  />
</MediaProvider>
```

### Environment:

- Framework: React
- Meta Framework: Vite
- Node: 18.0.0
- Device: Windows
- OS:  Windows 11
- Browser: Chrome@118

**Comment by ljs19923** [comment]
How do you import MediaProvider?
I have the @vidstack/react@0.6.13 and MediaProvider doesn't exist
