### ISSUE TITLE
Not possible to play MP4 videos where the URL doesn not end with .mp4

### ISSUE THREAD

**Issue by AgentSmith0** [vidstack/vidstack#952]
### Current Behavior:

MP4 URLs that do not end with .mp4 cannot be played.

### Expected Behavior:

Play any URL that is an MP4 file without having .mp4.

### Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Set MP4 URL as source without .mp4 at the end
2. See that the file does not get played

### Environment:

- Framework: CDN
- Device: Any
- OS: Any
- Browser: Any

**Comment by mihar-22** [comment]
It's `application/x-mpegurl`
